# Generated by Django 3.1.5 on 2021-01-29 16:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('receiver_url', models.URLField(null=True)),
                ('notification_interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('live', 'Live')], max_length=32)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('http', 'Http')], max_length=32)),
                ('teams', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
